package main;

public class smthing {
    public smthing(){
        String cos = "Największą siłą leżącą u podstawy Drogi Życia 6 jest miłość. To ona reguluje" +
                "całe życie, jest nieskończona i pozwala stanąć u boku swoich bliskich zawsze we" +
                "właściwym momencie. Mogą oni liczyć na wsparcie i pocieszenie, wysłuchanie" +
                "i podniesienie na duchu. Z tego względu numerologiczna 6 dąży do tego, by w jej" +
                "otoczeniu królowały piękno, zgoda, harmonia i spokój. Wyróżnia się fizyczną" +
                "atrakcyjnością i magnetyczną osobowością. Jako że dom i rodzina są tutaj w centrum"+
                ", obecność miłości, ciepła i dobrego słowa płynącego prosto z serca jest najwyższym błogostanem i poczuciem spełnienia. Miłość jest w tej wibracji niesiona bezinteresownie. Przekazanie wiedzy, mądrości i doświadczenia odbywa się w nadziei, że pomogą one ludziom przejść spokojnie ich drogę. Pogrążeni w smutku, cierpieniu i rozczarowaniu odnajdują tu współczucie, zrozumienie i słowa otuchy. Osoby z Drogą Życia 6 pozostają pod opieką Wenus, która reprezentuje piękno, symetrię, harmonię i sztukę. Z racji wysokiego poczucia estetyki, ludzie ci są koneserami piękna i dlatego starają się upiększać świat wokół. Kochają dom i ogród, uwielbiają zajmować się nimi i urządzać je, wkładając w wystrój i atmosferę całe swoje serce. Są niezwykle kreatywni i muszą znaleźć sposoby na konstruktywne wykorzystanie tej kreatywności. Wiele Szóstek jest niezwykle utalentowanych muzycznie, stąd często rozwijają swoje umiejętności poprzez grę na instrumentach. Silne przywiązanie do domu sprawia, że osoby te preferują wykonywać pracę, która pozwala im zachować kontakt z domem. Traktują go jako najpiękniejsze miejsce do życia, stąd często wybierają takie profesje, jak dekorator wnętrz czy ekspert feng shui. Jeśli pracują poza domem, wówczas miejsce pracy czynią takim, by czuli się w nim jak w domu. Bez względu na to, czym się Szóstki zajmują, istotny jest dla nich spokój. Dlatego też wolą zarządzać lub prowadzić własną firmę niż mieć nad sobą szefa. Naturalne poczucie odpowiedzialności i opiekuńczości czyni Szóstki wychowawcami, pielęgniarzami, wizjonerami i mistrzami sprawiedliwości. Dlatego na ich drodze pojawiają się ludzie z problemami, którzy proszą je o pomoc. Przydzielane są im również stanowiska wymagające odpowiedzialności, co pozwala wykorzystać wrodzone umiejętności i talenty w tych dziedzinach. Jeśli nie zdecydują się zostać rodzicem, pełnią tę rolę w inny sposób: jako nauczyciele i wychowawcy w przedszkolu, szkole i na uczelniach, lekarze i pielęgniarki, współpracownicy i przyjaciele, opiekunowie w domach pomocy roztaczający opiekę nad osobami słabszymi i chorymi, opiekunowie zwierząt domowych - dlatego szczególnie często towarzyszą im małe zwierzątka, jak koty, psy czy rodziny zyskuje dzięki nim szersze znaczenie. Jeśli tworzą związek małżeński, wolą spędzać czas z małżonkiem niż z przyjaciółmi. Jeśli są osobami samotnymi, dynamikę rodziny przenoszą do obszaru swojej aktywności. Kobieta Szóstka ma tendencję do przyciągania młodszych mężczyzn. Rozwiedziona kobieta Szóstka może zanadto angażować się w życie swoich dzieci i mieć trudności z postrzeganiem ich jako dorosłych. Nie jest zdrowe";
    }
}
